import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import Nav from "./components/Nav";
import Footer from "./components/Footer";
=======
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
>>>>>>> 9abe13dc891d6c42247cefbd4ddde745048d9846

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

<<<<<<< HEAD


=======
>>>>>>> 9abe13dc891d6c42247cefbd4ddde745048d9846
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${montserrat.className}   antialiased`}
      >
        <Nav/>
        {children}
        <Footer/>
=======
        className={`${montserrat.className} antialiased`}
      >
        <Nav />
        {children}
        <Footer />
>>>>>>> 9abe13dc891d6c42247cefbd4ddde745048d9846
      </body>
    </html>
  );
}
