import {  Montserrat, Sora } from "next/font/google";
import "./globals.css";
import { imageOptimizer } from "next/dist/server/image-optimizer";
import Nav from "@/components/Nav";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800","900"],
});

// const geistMono = montserrat({
//   variable: "--font-montserrat",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className}antialiased`}
      >
        {children}
      <Nav/>
      </body>
    </html>
  );
}
